apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ms-consumer
  labels:
    app: ms-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-consumer
  template:
    metadata:
      labels:
        app: ms-consumer
    spec:
      containers:
      - name: my-ms-consumer
        image: klinakuf/my-microsercvice-consumer:latest
        ports:
        - containerPort: 8080

